const { Client } = require('discord.js-selfbot-v13');
const fs = require('fs');
const path = require('path');
const { exec, spawn, execFile } = require('child_process');
const { 
    joinVoiceChannel, 
    createAudioPlayer, 
    createAudioResource, 
    AudioPlayerStatus, 
    VoiceConnectionStatus,
    StreamType
} = require('@discordjs/voice');
const play = require('play-dl');
const ffmpegPath = require('ffmpeg-static');
const yts = require('yt-search');

// Prepend ffmpeg-static to process.env.PATH so @discordjs/voice/prism-media can find it automatically
if (ffmpegPath && process.platform !== 'android') {
    const ffmpegDir = path.dirname(ffmpegPath);
    const separator = process.platform === 'win32' ? ';' : ':';
    process.env.PATH = `${ffmpegDir}${separator}${process.env.PATH}`;
}

// Load config
const configPath = path.join(__dirname, 'config.json');
if (!fs.existsSync(configPath)) {
    console.error('\x1b[31m[Error] config.json is missing! Please create it.\x1b[0m');
    process.exit(1);
}

const config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));

if (!config.token || config.token === 'YOUR_DISCORD_USER_TOKEN') {
    console.error('\x1b[31m[Error] Please set your actual Discord User Token in config.json!\x1b[0m');
    process.exit(1);
}

const client = new Client({
    checkUpdate: false,
    ws: {
        properties: {
            $os: 'Windows',
            $browser: 'Discord Client',
            $device: 'Desktop'
        }
    }
});

const prefix = config.prefix || '>';

// Setup Spotify credentials if available
if (config.spotify_client_id && config.spotify_client_secret) {
    play.setToken({
        spotify: {
            client_id: config.spotify_client_id,
            client_secret: config.spotify_client_secret
        }
    }).then(() => {
        console.log('\x1b[32m[Success] Spotify integration configured.\x1b[0m');
    }).catch(err => {
        console.warn(`\x1b[33m[Warning] Spotify setup failed: ${err.message}\x1b[0m`);
    });
} else {
    console.log('\x1b[33m[Info] Spotify credentials not set in config.json. Spotify URLs may not work.\x1b[0m');
}

// Helper to parse cookies from multiple formats (JSON, Netscape, Raw Header String)
function parseCookies(ytCookie) {
    if (!ytCookie) return '';
    
    // Case 1: If it's a JSON array or JSON string of array
    let cookiesArray = null;
    if (typeof ytCookie === 'string') {
        try {
            cookiesArray = JSON.parse(ytCookie);
        } catch (e) {}
    } else if (Array.isArray(ytCookie)) {
        cookiesArray = ytCookie;
    }
    
    if (cookiesArray && Array.isArray(cookiesArray)) {
        return cookiesArray.map(c => `${c.name}=${c.value}`).join('; ');
    }
    
    // Case 2: If it's a string, check if it's Netscape format (tab/space separated)
    if (typeof ytCookie === 'string') {
        const lines = ytCookie.split('\n');
        const netscapeCookies = [];
        for (let line of lines) {
            line = line.trim();
            if (!line || line.startsWith('#')) continue;
            
            const parts = line.split(/\s+/);
            if (parts.length >= 7) {
                const name = parts[5];
                const value = parts[6];
                netscapeCookies.push(`${name}=${value}`);
            }
        }
        if (netscapeCookies.length > 0) {
            return netscapeCookies.join('; ');
        }
        
        // Case 3: Raw cookie header string
        return ytCookie;
    }
    
    return '';
}

function writeNetscapeCookieFile(rawCookie, filePath) {
    let cookies = [];
    
    // Parse cookies into key-value pairs
    if (typeof rawCookie === 'string') {
        // Check if it's already a Netscape format
        if (rawCookie.includes('\t') || rawCookie.startsWith('#')) {
            fs.writeFileSync(filePath, rawCookie);
            return;
        }
        
        // Try parsing JSON array
        try {
            const parsed = JSON.parse(rawCookie);
            if (Array.isArray(parsed)) {
                cookies = parsed;
            }
        } catch (e) {
            // Semicolon separated header string
            const pairs = rawCookie.split(';');
            for (let pair of pairs) {
                const eqIdx = pair.indexOf('=');
                if (eqIdx !== -1) {
                    const name = pair.slice(0, eqIdx).trim();
                    const value = pair.slice(eqIdx + 1).trim();
                    if (name && value) {
                        cookies.push({ name, value });
                    }
                }
            }
        }
    } else if (Array.isArray(rawCookie)) {
        cookies = rawCookie;
    }
    
    // Write Netscape format
    let content = "# Netscape HTTP Cookie File\n# This file is generated by Ukulele Selfbot\n\n";
    for (let c of cookies) {
        const domain = '.youtube.com';
        const includeSub = 'TRUE';
        const path = '/';
        const secure = 'TRUE';
        const expiry = '0'; // session cookie
        content += `${domain}\t${includeSub}\t${path}\t${secure}\t${expiry}\t${c.name}\t${c.value}\n`;
    }
    
    fs.writeFileSync(filePath, content, 'utf-8');
}

// Setup YouTube cookies or browser extraction
if (config.youtube_cookies_from_browser) {
    console.log(`\x1b[32m[Success] YouTube cookie extraction enabled from browser: "${config.youtube_cookies_from_browser}".\x1b[0m`);
} else if (config.youtube_cookie) {
    const formattedCookie = parseCookies(config.youtube_cookie);
    
    // Generate Netscape cookies file for yt-dlp
    const cookiePath = path.join(__dirname, 'cookies.txt');
    try {
        writeNetscapeCookieFile(config.youtube_cookie, cookiePath);
        console.log('\x1b[32m[Success] Generated cookies.txt for yt-dlp.\x1b[0m');
    } catch (err) {
        console.warn(`\x1b[33m[Warning] Failed to generate cookies.txt: ${err.message}\x1b[0m`);
    }

    play.setToken({
        youtube: {
            cookie: formattedCookie
        }
    }).then(() => {
        console.log('\x1b[32m[Success] YouTube cookie configured for play-dl.\x1b[0m');
    }).catch(err => {
        console.warn(`\x1b[33m[Warning] YouTube cookie setup failed: ${err.message}\x1b[0m`);
    });
} else {
    console.log('\x1b[33m[Info] YouTube cookie not set and browser cookie extraction is disabled in config.json. If you get "Sign in to confirm you\'re not a bot" errors, please configure one of them.\x1b[0m');
}

// Setup SoundCloud integration
play.getFreeClientID().then(clientId => {
    play.setToken({
        soundcloud: {
            client_id: clientId
        }
    });
    console.log('\x1b[32m[Success] SoundCloud integration configured.\x1b[0m');
}).catch(err => {
    console.warn(`\x1b[33m[Warning] SoundCloud setup failed: ${err.message}\x1b[0m`);
});

// Helper to clean YouTube titles for a better search match on SoundCloud
function cleanTitleForSearch(title) {
    if (!title) return '';
    return title
        .replace(/\(.*?\)/g, '')
        .replace(/\[.*?\]/g, '')
        .replace(/official\s+video/gi, '')
        .replace(/official\s+music\s+video/gi, '')
        .replace(/music\s+video/gi, '')
        .replace(/lyric\s+video/gi, '')
        .replace(/lyrics/gi, '')
        .replace(/[|:\-–—]/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
}


// Music State
let queue = [];
let voiceConnection = null;
let audioPlayer = null;
let currentChildProcess = null;
let loopStatus = 'none'; // 'none' | 'song' | 'queue'
let currentVolume = 1.0;
let currentResource = null;

// Resolve query helper
// Helper to extract video metadata and direct stream URL using yt-dlp.exe
function getYoutubeInfo(videoUrl) {
    return new Promise((resolve, reject) => {
        const ytdlpPath = process.platform === 'android' ? 'yt-dlp' : path.join(__dirname, process.platform === 'win32' ? 'yt-dlp.exe' : 'yt-dlp');
        const args = ['--dump-json', '-f', 'bestaudio', '--js-runtimes', 'node', '--remote-components', 'ejs:github'];
        
        if (config.youtube_cookies_from_browser) {
            args.push('--cookies-from-browser', config.youtube_cookies_from_browser);
        } else {
            const cookiePath = path.join(__dirname, 'cookies.txt');
            if (fs.existsSync(cookiePath)) {
                args.push('--cookies', cookiePath);
            }
        }
        
        args.push(videoUrl);

        execFile(ytdlpPath, args, (error, stdout, stderr) => {
            if (error) {
                return reject(error);
            }
            try {
                const info = JSON.parse(stdout);
                resolve({
                    title: info.title || info.fulltitle || 'YouTube Stream',
                    streamUrl: info.url,
                    duration: info.duration || 0
                });
            } catch (e) {
                reject(new Error('Failed to parse yt-dlp output'));
            }
        });
    });
}

// Helper to extract playlist items using yt-dlp.exe
function getYoutubePlaylistVideos(playlistUrl) {
    return new Promise((resolve, reject) => {
        const ytdlpPath = process.platform === 'android' ? 'yt-dlp' : path.join(__dirname, process.platform === 'win32' ? 'yt-dlp.exe' : 'yt-dlp');
        const args = ['--flat-playlist', '--dump-json'];
        
        if (config.youtube_cookies_from_browser) {
            args.push('--cookies-from-browser', config.youtube_cookies_from_browser);
        } else {
            const cookiePath = path.join(__dirname, 'cookies.txt');
            if (fs.existsSync(cookiePath)) {
                args.push('--cookies', cookiePath);
            }
        }
        
        args.push(playlistUrl);

        // Increased maxBuffer to 10MB to support large playlists without buffer overflow
        execFile(ytdlpPath, args, { maxBuffer: 10 * 1024 * 1024 }, (error, stdout, stderr) => {
            if (error) {
                return reject(error);
            }
            try {
                const lines = stdout.trim().split('\n');
                const videos = [];
                for (const line of lines) {
                    if (!line.trim()) continue;
                    const info = JSON.parse(line);
                    videos.push({
                        title: info.title || 'YouTube Playlist Video',
                        url: info.url || `https://www.youtube.com/watch?v=${info.id}`,
                        id: info.id
                    });
                }
                resolve(videos);
            } catch (e) {
                reject(new Error('Failed to parse yt-dlp playlist output'));
            }
        });
    });
}

// Helper to automatically find target voice channel
async function getTargetVoiceChannel(message = null, targetOwnerId = null) {
    // 1. If command is from Discord, try to get the sender's voice channel
    if (message && message.member?.voice?.channel) {
        return message.member.voice.channel;
    }
    
    // 2. Otherwise, check all guilds to find if any owner is in a voice channel
    const ownerIds = targetOwnerId && targetOwnerId !== 'auto'
        ? [targetOwnerId]
        : (config.owner_ids || []);
        
    for (const ownerId of ownerIds) {
        for (const guild of client.guilds.cache.values()) {
            const voiceState = guild.voiceStates.cache.get(ownerId);
            if (voiceState && voiceState.channelId) {
                const channel = await client.channels.fetch(voiceState.channelId).catch(() => null);
                if (channel && (channel.type === 'GUILD_VOICE' || channel.type === 'GUILD_STAGE_VOICE')) {
                    return channel;
                }
            }
        }
    }
    
    return null;
}

// Unified helper to connect to a voice channel and set up stateChange listener
function connectToVoiceChannel(channel) {
    if (voiceConnection) {
        voiceConnection.destroy();
        voiceConnection = null;
    }

    voiceConnection = joinVoiceChannel({
        channelId: channel.id,
        guildId: channel.guild.id,
        adapterCreator: channel.guild.voiceAdapterCreator,
    });

    voiceConnection.on('stateChange', (oldState, newState) => {
        if (newState.status === VoiceConnectionStatus.Disconnected) {
            if (voiceConnection) {
                voiceConnection.destroy();
                voiceConnection = null;
                audioPlayer = null;
                currentResource = null;
                queue = [];
                loopStatus = 'none';
                if (currentChildProcess) {
                    currentChildProcess.kill();
                    currentChildProcess = null;
                }
                console.log('\n\x1b[33m[Voice Info] Disconnected from voice channel.\x1b[0m');
            }
        }
    });

    return voiceConnection;
}

// Resolve query helper
async function resolveSong(query) {
    // Helper to sanitize URL for play-dl (ensures www. is present for youtube.com links)
    const sanitizeUrl = (url) => {
        if (url && /youtube\.com/i.test(url) && !/www\.youtube\.com/i.test(url)) {
            return url.replace(/youtube\.com/i, 'www.youtube.com');
        }
        return url;
    };

    // Spotify Track
    if (play.sp_validate(query) === 'track') {
        try {
            if (!config.spotify_client_id || !config.spotify_client_secret) {
                throw new Error(
                    'Spotify Client ID/Secret are not configured in config.json.\n\n' +
                    '>>> ╭━━━ **Spotify Setup Guide** ━━━╮\n' +
                    '1. Go to: **https://developer.spotify.com/dashboard**\n' +
                    '2. Create an App to get your Client ID & Secret.\n' +
                    '3. Add "spotify_client_id" and "spotify_client_secret" to config.json.\n' +
                    '╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯'
                );
            }
            
            const spotifyData = await play.spotify(query);
            const searchKeyword = `${spotifyData.name} ${spotifyData.artists.map(a => a.name).join(' ')}`;
            const ytInfo = await yts(searchKeyword);
            if (ytInfo && ytInfo.videos && ytInfo.videos.length > 0) {
                const videoUrl = sanitizeUrl(ytInfo.videos[0].url);
                try {
                    const directInfo = await getYoutubeInfo(videoUrl);
                    return [{
                        title: `${spotifyData.name} - ${spotifyData.artists.map(a => a.name).join(', ')}`,
                        url: directInfo.streamUrl,
                        originalUrl: videoUrl,
                        query: query,
                        source: 'youtube'
                    }];
                } catch (e) {
                    return [{
                        title: `${spotifyData.name} - ${spotifyData.artists.map(a => a.name).join(', ')}`,
                        url: videoUrl,
                        originalUrl: videoUrl,
                        query: query,
                        source: 'youtube'
                    }];
                }
            } else {
                throw new Error('Could not find matching video on YouTube.');
            }
        } catch (err) {
            throw new Error(`Spotify resolution failed: ${err.message}`);
        }
    }
    
    // Spotify Playlist or Album
    if (play.sp_validate(query) === 'playlist' || play.sp_validate(query) === 'album') {
        try {
            if (!config.spotify_client_id || !config.spotify_client_secret) {
                throw new Error(
                    'Spotify Client ID/Secret are not configured in config.json.\n\n' +
                    '>>> ╭━━━ **Spotify Setup Guide** ━━━╮\n' +
                    '1. Go to: **https://developer.spotify.com/dashboard**\n' +
                    '2. Create an App to get your Client ID & Secret.\n' +
                    '3. Add "spotify_client_id" and "spotify_client_secret" to config.json.\n' +
                    '╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯'
                );
            }
            
            const spotifyData = await play.spotify(query);
            const tracks = await spotifyData.all_tracks();
            
            if (!tracks || tracks.length === 0) {
                throw new Error('Spotify playlist/album is empty or has no accessible tracks.');
            }
            
            return tracks.map(track => {
                const artistsStr = track.artists.map(a => a.name).join(', ');
                const title = `${track.name} - ${artistsStr}`;
                return {
                    title: title,
                    url: null, // resolved dynamically in playSong
                    originalUrl: null,
                    query: query,
                    source: 'spotify',
                    searchKeyword: `${track.name} ${artistsStr}`
                };
            });
        } catch (err) {
            throw new Error(`Spotify playlist resolution failed: ${err.message}`);
        }
    }

    // YouTube Playlist
    const isYoutubePlaylist = play.yt_validate(query) === 'playlist' || (query.includes('list=') && (query.includes('youtube.com') || query.includes('youtu.be')));
    if (isYoutubePlaylist) {
        try {
            const playlistUrl = sanitizeUrl(query);
            let playlistVideos = [];
            try {
                playlistVideos = await getYoutubePlaylistVideos(playlistUrl);
            } catch (ytdlErr) {
                console.warn('\x1b[33m[Warning] yt-dlp playlist fetch failed, falling back to play-dl:\x1b[0m', ytdlErr.message);
                const playlistInfo = await play.playlist_info(playlistUrl);
                const allVideos = await playlistInfo.all_videos();
                playlistVideos = allVideos.map(video => ({
                    title: video.title,
                    url: video.url || `https://www.youtube.com/watch?v=${video.id}`,
                    id: video.id
                }));
            }

            if (!playlistVideos || playlistVideos.length === 0) {
                throw new Error('YouTube playlist is empty or could not be fetched.');
            }
            return playlistVideos.map(video => ({
                title: video.title,
                url: video.url,
                originalUrl: video.url,
                query: query,
                source: 'youtube'
            }));
        } catch (err) {
            throw new Error(`YouTube playlist resolution failed: ${err.message}`);
        }
    }

    // YouTube Video URL
    if (play.yt_validate(query) === 'video') {
        const videoUrl = sanitizeUrl(query);
        try {
            const ytInfo = await getYoutubeInfo(videoUrl);
            return [{
                title: ytInfo.title,
                url: ytInfo.streamUrl,
                originalUrl: videoUrl,
                query: query,
                source: 'youtube'
            }];
        } catch (err) {
            return [{
                title: 'YouTube Stream',
                url: videoUrl,
                originalUrl: videoUrl,
                query: query,
                source: 'youtube'
            }];
        }
    }

    // Search Query
    try {
        const ytInfo = await yts(query);
        if (ytInfo && ytInfo.videos && ytInfo.videos.length > 0) {
            const videoUrl = sanitizeUrl(ytInfo.videos[0].url);
            try {
                const directInfo = await getYoutubeInfo(videoUrl);
                return [{
                    title: directInfo.title,
                    url: directInfo.streamUrl,
                    originalUrl: videoUrl,
                    query: query,
                    source: 'youtube'
                }];
            } catch (e) {
                return [{
                    title: ytInfo.videos[0].title,
                    url: videoUrl,
                    originalUrl: videoUrl,
                    query: query,
                    source: 'youtube'
                }];
            }
        } else {
            throw new Error('No results found on YouTube.');
        }
    } catch (err) {
        throw new Error(`Search failed: ${err.message}`);
    }
}

// Helper to send a message that deletes itself after a delay to prevent spam
function sendTempResponse(channel, content, delay = 10000) {
    if (!channel) return;
    channel.send(content)
        .then(msg => {
            setTimeout(() => {
                msg.delete().catch(() => {});
            }, delay);
        })
        .catch(console.error);
}

// Helper to spawn yt-dlp.exe and return its stdout stream
function getYoutubeStream(videoUrl) {
    const ytdlpPath = process.platform === 'android' ? 'yt-dlp' : path.join(__dirname, process.platform === 'win32' ? 'yt-dlp.exe' : 'yt-dlp');
    const args = [
        '--no-progress',
        '-f', 'bestaudio',
        '-o', '-',
        '--js-runtimes', 'node',
        '--remote-components', 'ejs:github',
    ];
    
    if (config.youtube_cookies_from_browser) {
        args.push('--cookies-from-browser', config.youtube_cookies_from_browser);
    } else {
        const cookiePath = path.join(__dirname, 'cookies.txt');
        if (fs.existsSync(cookiePath)) {
            args.push('--cookies', cookiePath);
        }
    }
    
    args.push(videoUrl);

    const child = spawn(ytdlpPath, args, {
        stdio: ['ignore', 'pipe', 'pipe']
    });

    child.stderr.on('data', (data) => {
        const msg = data.toString().trim();
        if (!msg.includes('No supported JavaScript runtime')) {
            console.warn(`[yt-dlp stderr] ${msg}`);
        }
    });

    child.on('error', (err) => {
        console.error(`[yt-dlp error] ${err.message}`);
    });

    return child;
}

// Play song helper
function playSong(textChannel) {
    if (queue.length === 0) {
        if (currentChildProcess) {
            currentChildProcess.kill();
            currentChildProcess = null;
        }
        if (voiceConnection) {
            voiceConnection.destroy();
            voiceConnection = null;
            audioPlayer = null;
            currentResource = null;
        }
        if (textChannel) {
            sendTempResponse(textChannel, '🎶 **Queue is empty. Disconnected from voice channel.**', 8000);
        }
        return;
    }

    const song = queue[0];

    // Helper to run play logic once song has a stream URL
    const playStream = () => {
        if (!audioPlayer) {
            audioPlayer = createAudioPlayer();
            if (voiceConnection) {
                voiceConnection.subscribe(audioPlayer);
            }

            audioPlayer.on(AudioPlayerStatus.Idle, () => {
                if (currentChildProcess) {
                    currentChildProcess.kill();
                    currentChildProcess = null;
                }
                if (loopStatus === 'song') {
                    playSong(textChannel);
                } else if (loopStatus === 'queue') {
                    const currentSong = queue.shift();
                    if (currentSong) {
                        if (currentSong.originalUrl === null && currentSong.source === 'youtube') {
                            currentSong.source = 'spotify';
                            currentSong.url = null;
                        }
                        queue.push(currentSong);
                    }
                    playSong(textChannel);
                } else {
                    queue.shift();
                    playSong(textChannel);
                }
            });

            audioPlayer.on('error', error => {
                console.error(`AudioPlayer error: ${error.message}`);
                if (currentChildProcess) {
                    currentChildProcess.kill();
                    currentChildProcess = null;
                }
                if (queue.length === 0 || queue[0] !== song) return;
                if (textChannel) {
                    sendTempResponse(textChannel, `❌ **Playback error:** ${error.message}`, 8000);
                }
                if (loopStatus === 'queue') {
                    const currentSong = queue.shift();
                    if (currentSong) {
                        if (currentSong.originalUrl === null && currentSong.source === 'youtube') {
                            currentSong.source = 'spotify';
                            currentSong.url = null;
                        }
                        queue.push(currentSong);
                    }
                    playSong(textChannel);
                } else {
                    queue.shift();
                    playSong(textChannel);
                }
            });
        }

        if (textChannel) {
            sendTempResponse(textChannel, `🎶 **Now playing:** \`${song.title}\``, 10000);
        }

        const runSoundCloudFallback = async (originalErr) => {
            if (currentChildProcess) {
                currentChildProcess.kill();
                currentChildProcess = null;
            }
            if (queue.length === 0 || queue[0] !== song) return;
            
            const isYoutubeUrl = /youtube\.com|youtu\.be/i.test(song.url) || (song.originalUrl && /youtube\.com/i.test(song.originalUrl));
            // Fallback to SoundCloud if YouTube streaming fails
            if (isYoutubeUrl) {
                if (textChannel) {
                    sendTempResponse(textChannel, `⚠️ **YouTube stream blocked. Trying SoundCloud fallback for:** \`${song.title}\`...`, 5000);
                }
                try {
                    // Determine best search query (use original query if it was not a URL, otherwise use clean title)
                    let searchQuery = cleanTitleForSearch(song.title);
                    if (song.query && !song.query.startsWith('http')) {
                        searchQuery = song.query;
                    }
                    
                    console.log(`Attempting SoundCloud fallback for: "${searchQuery}" (derived from: "${song.title}")`);
                    const scResults = await play.search(searchQuery, { source: { soundcloud: 'tracks' }, limit: 1 });
                    if (scResults && scResults.length > 0) {
                        const scStream = await play.stream(scResults[0].url);

                        const resource = createAudioResource(scStream.stream, {
                            inputType: scStream.type,
                            inlineVolume: true
                        });
                        if (resource.volume) {
                            resource.volume.setVolume(currentVolume);
                        }
                        currentResource = resource;
                        audioPlayer.play(resource);
                        if (textChannel) {
                            sendTempResponse(textChannel, `🎶 **Now playing (SoundCloud):** \`${scResults[0].name}\``, 10000);
                        }
                        return; // Successfully played fallback!
                    }
                } catch (scErr) {
                    console.error(`SoundCloud fallback failed: ${scErr.message}`);
                }
            }

            if (textChannel) {
                sendTempResponse(textChannel, `❌ **Failed to stream song:** ${originalErr.message}`, 8000);
            }
            queue.shift();
            playSong(textChannel);
        };

        const isYoutubeUrl = /youtube\.com|youtu\.be/i.test(song.url) || (song.originalUrl && /youtube\.com|youtu\.be/i.test(song.originalUrl)) || /googlevideo\.com/i.test(song.url);

        if (isYoutubeUrl) {
            if (currentChildProcess) {
                currentChildProcess.kill();
                currentChildProcess = null;
            }

            try {
                const ytUrl = song.originalUrl || song.url;
                const child = getYoutubeStream(ytUrl);
                currentChildProcess = child;

                const resource = createAudioResource(child.stdout, {
                    inputType: StreamType.Arbitrary,
                    inlineVolume: true
                });
                if (resource.volume) {
                    resource.volume.setVolume(currentVolume);
                }
                currentResource = resource;
                audioPlayer.play(resource);
            } catch (err) {
                console.error(`yt-dlp spawning error for ${song.title}: ${err.message}`);
                runSoundCloudFallback(err);
            }
        } else {
            if (currentChildProcess) {
                currentChildProcess.kill();
                currentChildProcess = null;
            }

            // Non-YouTube streams (SoundCloud, etc.)
            play.stream(song.url)
                .then(stream => {
                    const resource = createAudioResource(stream.stream, {
                        inputType: stream.type,
                        inlineVolume: true
                    });
                    if (resource.volume) {
                        resource.volume.setVolume(currentVolume);
                    }
                    currentResource = resource;
                    audioPlayer.play(resource);
                })
                .catch(async err => {
                    console.error(`play-dl stream error for ${song.title}: ${err.message}`);
                    await runSoundCloudFallback(err);
                });
        }
    };

    // Spotify resolution dynamic logic
    if (song.source === 'spotify' && !song.url) {
        const sanitizeUrl = (url) => {
            if (url && /youtube\.com/i.test(url) && !/www\.youtube\.com/i.test(url)) {
                return url.replace(/youtube\.com/i, 'www.youtube.com');
            }
            return url;
        };

        if (textChannel) {
            sendTempResponse(textChannel, `🔍 **Searching YouTube for Spotify track:** \`${song.title}\`...`, 5000);
        }

        yts(song.searchKeyword || song.title)
            .then(async (ytInfo) => {
                if (queue.length === 0 || queue[0] !== song) return; // queue state changed
                if (ytInfo && ytInfo.videos && ytInfo.videos.length > 0) {
                    const videoUrl = sanitizeUrl(ytInfo.videos[0].url);
                    try {
                        const directInfo = await getYoutubeInfo(videoUrl);
                        song.url = directInfo.streamUrl;
                        song.originalUrl = videoUrl;
                    } catch (e) {
                        song.url = videoUrl;
                        song.originalUrl = videoUrl;
                    }
                    song.source = 'youtube';
                    playStream();
                } else {
                    throw new Error('No search results found on YouTube.');
                }
            })
            .catch(async (err) => {
                if (queue.length === 0 || queue[0] !== song) return; // queue state changed
                console.error(`Dynamic Spotify resolution failed for ${song.title}:`, err.message);
                
                // Fallback to SoundCloud search directly
                if (textChannel) {
                    sendTempResponse(textChannel, `⚠️ **YouTube search failed for Spotify track. Trying SoundCloud...**`, 5000);
                }
                try {
                    const scResults = await play.search(song.title, { source: { soundcloud: 'tracks' }, limit: 1 });
                    if (scResults && scResults.length > 0) {
                        const scStream = await play.stream(scResults[0].url);

                        if (!audioPlayer) {
                            audioPlayer = createAudioPlayer();
                            if (voiceConnection) {
                                voiceConnection.subscribe(audioPlayer);
                            }
                            
                            audioPlayer.on(AudioPlayerStatus.Idle, () => {
                                if (currentChildProcess) {
                                    currentChildProcess.kill();
                                    currentChildProcess = null;
                                }
                                if (loopStatus === 'song') {
                                    playSong(textChannel);
                                } else if (loopStatus === 'queue') {
                                    const currentSong = queue.shift();
                                    if (currentSong) {
                                        if (currentSong.originalUrl === null && currentSong.source === 'youtube') {
                                            currentSong.source = 'spotify';
                                            currentSong.url = null;
                                        }
                                        queue.push(currentSong);
                                    }
                                    playSong(textChannel);
                                } else {
                                    queue.shift();
                                    playSong(textChannel);
                                }
                            });

                            audioPlayer.on('error', error => {
                                console.error(`AudioPlayer error: ${error.message}`);
                                if (currentChildProcess) {
                                    currentChildProcess.kill();
                                    currentChildProcess = null;
                                }
                                if (queue.length === 0 || queue[0] !== song) return;
                                if (textChannel) {
                                    sendTempResponse(textChannel, `❌ **Playback error:** ${error.message}`, 8000);
                                }
                                if (loopStatus === 'queue') {
                                    const currentSong = queue.shift();
                                    if (currentSong) {
                                        if (currentSong.originalUrl === null && currentSong.source === 'youtube') {
                                            currentSong.source = 'spotify';
                                            currentSong.url = null;
                                        }
                                        queue.push(currentSong);
                                    }
                                    playSong(textChannel);
                                } else {
                                    queue.shift();
                                    playSong(textChannel);
                                }
                            });
                        }

                        if (textChannel) {
                            sendTempResponse(textChannel, `🎶 **Now playing (SoundCloud):** \`${scResults[0].name}\``, 10000);
                        }

                        const resource = createAudioResource(scStream.stream, {
                            inputType: scStream.type,
                            inlineVolume: true
                        });
                        if (resource.volume) {
                            resource.volume.setVolume(currentVolume);
                        }
                        currentResource = resource;
                        audioPlayer.play(resource);
                        return;
                    }
                } catch (scErr) {
                    console.error(`SoundCloud fallback failed: ${scErr.message}`);
                }

                if (textChannel) {
                    sendTempResponse(textChannel, `❌ **Failed to resolve Spotify track:** \`${song.title}\``, 8000);
                }
                queue.shift();
                playSong(textChannel);
            });
    } else {
        playStream();
    }
}

// Helper to send response (edit if own message, otherwise send new message) and auto-delete after a delay
async function sendResponse(originalMsg, content, deleteDelay = 15000) {
    let responseMsg = null;
    if (originalMsg.author.id === client.user.id) {
        try {
            responseMsg = await originalMsg.edit(content);
        } catch (err) {
            responseMsg = await originalMsg.channel.send(content).catch(console.error);
        }
    } else {
        responseMsg = await originalMsg.channel.send(content).catch(console.error);
    }
    
    // Auto-delete response after delay
    if (responseMsg && deleteDelay) {
        setTimeout(() => {
            responseMsg.delete().catch(() => {});
        }, deleteDelay);
    }
    
    // Also delete the trigger message to prevent channel spam
    if (originalMsg && originalMsg.deletable) {
        setTimeout(() => {
            originalMsg.delete().catch(() => {});
        }, 3000);
    }
    
    return responseMsg;
}

client.on('ready', () => {
    console.log('\n\x1b[36m==================================================\x1b[0m');
    console.log(`\x1b[32m[Success] logged in as: ${client.user.tag}\x1b[0m`);
    console.log(`\x1b[35m[Info] ID: ${client.user.id}\x1b[0m`);
    console.log(`\x1b[33m[Info] Prefix set to: ${prefix}\x1b[0m`);
    console.log('\x1b[36m==================================================\n\x1b[0m');
    
    startConsoleListener();
    startWebServer();
});

client.on('messageCreate', async (message) => {
    if (!message.content.startsWith(prefix)) return;

    // Log the command attempt to terminal for easy user ID tracking
    console.log(`\n\x1b[35m[Command Attempt]\x1b[0m from: ${message.author.tag} (ID: ${message.author.id}) - Content: "${message.content}"`);

    const allowedUsers = [client.user.id, ...(config.owner_ids || [])];
    if (!allowedUsers.includes(message.author.id)) return;

    const args = message.content.slice(prefix.length).trim().split(/ +/);
    const command = args.shift().toLowerCase();

    // Help Command
    if (command === 'help') {
        const helpMessage = 
`**🎸 Ukulele Self-Bot Commands:**
• \`${prefix}help\` - Shows this help menu.
• \`${prefix}ping\` - Checks the bot API latency.
• \`${prefix}status <playing|streaming|listening|watching|clear> <text>\` - Sets your status.
• \`${prefix}embed <title> | <description>\` - Sends a stylized blockquote message.
• \`${prefix}purge <count>\` - Deletes your last N messages in this channel.
• \`${prefix}info\` - Displays self-bot info.
• \`${prefix}play <song title|URL>\` - Plays a song from YouTube/Spotify in your voice channel.
• \`${prefix}skip\` - Skips the current song.
• \`${prefix}stop\` - Stops music, clears queue, and leaves voice channel.
• \`${prefix}pause\` - Pauses music.
• \`${prefix}resume\` - Resumes paused music.
• \`${prefix}queue\` - Shows the current playback queue.
• \`${prefix}loop [off|queue|song]\` - Toggle loop status or set specific mode.
• \`${prefix}shuffle\` - Shuffles upcoming tracks in the queue.
• \`${prefix}volume [0-200]\` - View or set volume level (default 100).`;
        
        await sendResponse(message, helpMessage);
    }

    // Ping Command
    if (command === 'ping') {
        const start = Date.now();
        const resMsg = await sendResponse(message, '🏓 Pinging...');
        const latency = Date.now() - start;
        const pongText = `🏓 **Pong!**\n• Edit Latency: \`${latency}ms\`\n• API Latency: \`${Math.round(client.ws.ping)}ms\``;
        if (resMsg && resMsg.editable) {
            await resMsg.edit(pongText).catch(console.error);
        } else {
            await message.channel.send(pongText).catch(console.error);
        }
    }

    // Status Command
    if (command === 'status') {
        const type = args.shift()?.toLowerCase();
        const text = args.join(' ');

        if (!type || (type !== 'clear' && !text)) {
            return sendResponse(message, `❌ **Usage:** \`${prefix}status <playing|streaming|listening|watching|clear> [text]\``);
        }

        try {
            if (type === 'clear') {
                client.user.setPresence({ activities: [] });
                await sendResponse(message, '✅ **Status cleared!**');
            } else {
                let activityType;
                let extraOpts = {};

                if (type === 'playing') activityType = 'PLAYING';
                else if (type === 'streaming') {
                    activityType = 'STREAMING';
                    extraOpts.url = 'https://www.twitch.tv/nocopyrightsounds';
                }
                else if (type === 'listening') activityType = 'LISTENING';
                else if (type === 'watching') activityType = 'WATCHING';

                client.user.setPresence({
                    activities: [{
                        name: text,
                        type: activityType,
                        ...extraOpts
                    }]
                });

                await sendResponse(message, `✅ **Status updated to:** \`${type.toUpperCase()}: ${text}\``);
            }
        } catch (error) {
            console.error(error);
            await sendResponse(message, `❌ **Failed to update status:** ${error.message}`);
        }
    }

    // Embed/Stylized Command
    if (command === 'embed') {
        const text = args.join(' ');
        if (!text) {
            return sendResponse(message, `❌ **Usage:** \`${prefix}embed <title> | <description>\``);
        }

        const parts = text.split('|');
        const title = parts[0]?.trim();
        const desc = parts[1]?.trim() || '';

        const embedStyle = 
`>>> ╭━━━ **${title}** ━━━╮
${desc}
╰━━━━━━━━━━━━━━━━━╯`;
        await sendResponse(message, embedStyle);
    }

    // Purge Command
    if (command === 'purge') {
        const count = parseInt(args[0]);

        if (isNaN(count) || count <= 0) {
            return sendResponse(message, `❌ **Usage:** \`${prefix}purge <number_of_messages>\``);
        }

        await message.delete().catch(() => {}); // Delete the command message itself first

        const messages = await message.channel.messages.fetch({ limit: 100 });
        const userMessages = messages.filter(m => m.author.id === client.user.id).first(count);

        for (const msg of userMessages) {
            try {
                await msg.delete();
                await new Promise(resolve => setTimeout(resolve, 800));
            } catch (err) {
                console.error(`Failed to delete message: ${err.message}`);
            }
        }
    }

    // Info Command
    if (command === 'info') {
        const infoMsg = 
`🤖 **Darshon Music Player Version 1.0.0**
• **Developer:** Customized for you
• **Library:** \`discord.js-selfbot-v13\`
• **Runtime:** \`Node.js ${process.version}\`
• **Guilds:** \`${client.guilds.cache.size}\`
• **Uptime:** \`${Math.round(client.uptime / 60000)} minutes\``;
        await sendResponse(message, infoMsg);
    }

    // Play Command
    if (command === 'play') {
        const query = args.join(' ');
        if (!query) {
            return sendResponse(message, `❌ **Usage:** \`${prefix}play <song title|YouTube Link|Spotify Link>\``);
        }

        const voiceChannel = await getTargetVoiceChannel(message);
        if (!voiceChannel) {
            return sendResponse(message, '❌ **You must be in a voice channel or an owner must be in a voice channel to play music!**');
        }

        const searchStatusMsg = await sendResponse(message, `🔍 **Searching:** \`${query}\`...`);

        try {
            const songs = await resolveSong(query);
            
            if (!voiceConnection) {
                connectToVoiceChannel(voiceChannel);
            }

            queue.push(...songs);

            if (queue.length === songs.length) {
                if (searchStatusMsg && searchStatusMsg.deletable) {
                    await searchStatusMsg.delete().catch(() => {});
                }
                playSong(message.channel);
            } else {
                const addedMsg = songs.length > 1 
                    ? `📝 **Added playlist:** \`${songs.length}\` songs added to queue.`
                    : `📝 **Added to queue:** \`${songs[0].title}\` (Position: \`${queue.length - 1}\`)`;
                if (searchStatusMsg && searchStatusMsg.editable) {
                    await searchStatusMsg.edit(addedMsg).catch(console.error);
                } else {
                    await message.channel.send(addedMsg).catch(console.error);
                }
            }
        } catch (error) {
            console.error(error);
            if (searchStatusMsg && searchStatusMsg.editable) {
                await searchStatusMsg.edit(`❌ **Error:** ${error.message}`).catch(console.error);
            } else {
                await message.channel.send(`❌ **Error:** ${error.message}`).catch(console.error);
            }
        }
    }

    // Skip Command
    if (command === 'skip') {
        if (!voiceConnection || !audioPlayer) {
            return sendResponse(message, '❌ **No music is currently playing!**');
        }
        await sendResponse(message, '⏭️ **Skipping current song...**');
        if (currentChildProcess) {
            currentChildProcess.kill();
            currentChildProcess = null;
        }
        audioPlayer.stop();
    }


    // Stop Command
    if (command === 'stop') {
        if (!voiceConnection) {
            return sendResponse(message, '❌ **Bot is not in a voice channel!**');
        }
        await sendResponse(message, '🛑 **Stopping music and leaving voice channel...**');
        queue = [];
        if (currentChildProcess) {
            currentChildProcess.kill();
            currentChildProcess = null;
        }
        if (audioPlayer) {
            audioPlayer.stop();
        }
        if (voiceConnection) {
            voiceConnection.destroy();
            voiceConnection = null;
            audioPlayer = null;
            currentResource = null;
        }
    }

    // Pause Command
    if (command === 'pause') {
        if (!audioPlayer || audioPlayer.state.status === AudioPlayerStatus.Paused) {
            return sendResponse(message, '❌ **Music is already paused or not playing!**');
        }
        audioPlayer.pause();
        await sendResponse(message, '⏸️ **Music paused.**');
    }

    // Resume Command
    if (command === 'resume') {
        if (!audioPlayer || audioPlayer.state.status !== AudioPlayerStatus.Paused) {
            return sendResponse(message, '❌ **Music is not paused!**');
        }
        audioPlayer.unpause();
        await sendResponse(message, '▶️ **Music resumed.**');
    }

    // Queue Command
    if (command === 'queue') {
        if (queue.length === 0) {
            return sendResponse(message, '🎶 **The queue is currently empty.**');
        }
        
        let queueMsg = `🎶 **Current Play Queue:**\n`;
        queueMsg += `• **Now Playing:** \`${queue[0].title}\`\n\n`;
        
        if (queue.length > 1) {
            queueMsg += `**Up Next:**\n`;
            for (let i = 1; i < queue.length; i++) {
                queueMsg += `**${i}.** \`${queue[i].title}\`\n`;
                if (i >= 10) {
                    queueMsg += `...and ${queue.length - 11} more songs in queue.`;
                    break;
                }
            }
        }
        
        await sendResponse(message, queueMsg);
    }

    // Loop Command
    if (command === 'loop') {
        const mode = args[0]?.toLowerCase();
        
        if (!mode) {
            if (loopStatus === 'none') loopStatus = 'queue';
            else if (loopStatus === 'queue') loopStatus = 'song';
            else loopStatus = 'none';
        } else if (['off', 'none', 'clear'].includes(mode)) {
            loopStatus = 'none';
        } else if (['queue', 'all'].includes(mode)) {
            loopStatus = 'queue';
        } else if (['song', 'track', 'one'].includes(mode)) {
            loopStatus = 'song';
        } else {
            return sendResponse(message, `❌ **Invalid mode!** Usage: \`${prefix}loop <off|queue|song>\``);
        }

        const statusMap = {
            'none': 'Disabled (Normal playback)',
            'queue': 'Repeat entire queue (Queue Loop)',
            'song': 'Repeat current track (Song Loop)'
        };
        
        const loopEmbed = 
`>>> ╭━━━ **Loop Mode Updated** ━━━╮
🔁 **Status:** \`${statusMap[loopStatus]}\`
╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯`;
        await sendResponse(message, loopEmbed);
    }

    // Shuffle Command
    if (command === 'shuffle') {
        if (queue.length <= 2) {
            return sendResponse(message, '❌ **Not enough songs in the queue to shuffle!**');
        }
        
        const nowPlaying = queue[0];
        const toShuffle = queue.slice(1);
        
        for (let i = toShuffle.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [toShuffle[i], toShuffle[j]] = [toShuffle[j], toShuffle[i]];
        }
        
        queue = [nowPlaying, ...toShuffle];
        
        const shuffleEmbed = 
`>>> ╭━━━ **Queue Shuffled** ━━━╮
🔀 Shuffled \`${toShuffle.length}\` upcoming songs!
╰━━━━━━━━━━━━━━━━━━━━━━━━━━━╯`;
        await sendResponse(message, shuffleEmbed);
    }

    // Volume Command
    if (command === 'volume' || command === 'vol' || command === 'v') {
        const val = args[0];
        if (!val) {
            return sendResponse(message, `🔊 **Current Volume:** \`${Math.round(currentVolume * 100)}%\``);
        }
        const parsed = parseInt(val, 10);
        if (isNaN(parsed) || parsed < 0 || parsed > 200) {
            return sendResponse(message, `❌ **Invalid volume!** Specify a number between \`0\` and \`200\`.`);
        }
        currentVolume = parsed / 100;
        if (currentResource && currentResource.volume) {
            currentResource.volume.setVolume(currentVolume);
        }
        await sendResponse(message, `🔊 **Volume updated to:** \`${parsed}%\``);
    }
});

const readline = require('readline');

function startConsoleListener() {
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
        prompt: 'SelfBot-Console> '
    });

    // Make sure we prompt cleanly after initial startup logs
    setTimeout(() => {
        rl.prompt();
    }, 1000);

    rl.on('line', async (line) => {
        const input = line.trim();
        if (!input) {
            rl.prompt();
            return;
        }

        const args = input.split(/ +/);
        const command = args.shift().toLowerCase();
        const query = args.join(' ');

        if (command === 'help') {
            console.log('\n\x1b[36m--- Console Commands --- \x1b[0m');
            console.log('• join <channel_id>      - Connect bot to voice channel');
            console.log('• play <search or url>   - Play a song (must be in VC first)');
            console.log('• skip                   - Skip the current song');
            console.log('• stop                   - Stop playing and disconnect');
            console.log('• pause                  - Pause music');
            console.log('• resume                 - Resume music');
            console.log('• queue                  - View current queue');
            console.log('• loop <off|queue|song>  - Toggle/set loop status');
            console.log('• shuffle                - Shuffle the queue');
            console.log('• volume [0-200]         - View or set volume level');
            console.log('• help                   - Show this menu\n');
        } 
        else if (command === 'join') {
            if (!query) {
                console.log('\x1b[31m[Console Error] Usage: join <channel_id>\x1b[0m');
            } else {
                await joinConsoleVC(query);
            }
        } 
        else if (command === 'play') {
            if (!query) {
                console.log('\x1b[31m[Console Error] Usage: play <song name or url>\x1b[0m');
            } else {
                if (!voiceConnection) {
                    const targetVc = await getTargetVoiceChannel(null);
                    if (targetVc) {
                        connectToVoiceChannel(targetVc);
                        console.log(`\x1b[32m[Console Success] Auto-connected to Voice Channel: "${targetVc.name}"\x1b[0m`);
                    } else {
                        console.log('\x1b[31m[Console Error] Bot is not in a voice channel and no owner is in a voice channel. Use "join <channel_id>" first.\x1b[0m');
                        rl.prompt();
                        return;
                    }
                }
                console.log(`\x1b[36m[Console Info] Searching for "${query}"...\x1b[0m`);
                try {
                    const songs = await resolveSong(query);
                    queue.push(...songs);
                    if (songs.length > 1) {
                        console.log(`\x1b[32m[Console Success] Resolved and queued playlist: ${songs.length} songs added.\x1b[0m`);
                    } else {
                        console.log(`\x1b[32m[Console Success] Resolved and queued: ${songs[0].title}\x1b[0m`);
                    }
                    if (queue.length === songs.length) {
                        playSong(null);
                    }
                } catch (err) {
                    console.log(`\x1b[31m[Console Error] Play failed: ${err.message}\x1b[0m`);
                }
            }
        } 
        else if (command === 'skip') {
            if (!voiceConnection || !audioPlayer) {
                console.log('\x1b[31m[Console Error] No music is playing!\x1b[0m');
            } else {
                console.log('⏭️ Skipping current song...');
                if (currentChildProcess) {
                    currentChildProcess.kill();
                    currentChildProcess = null;
                }
                audioPlayer.stop();
            }
        } 
        else if (command === 'stop') {
            if (!voiceConnection) {
                console.log('\x1b[31m[Console Error] Bot is not in a voice channel!\x1b[0m');
            } else {
                console.log('🛑 Stopping music and leaving voice channel...');
                queue = [];
                if (currentChildProcess) {
                    currentChildProcess.kill();
                    currentChildProcess = null;
                }
                if (audioPlayer) {
                    audioPlayer.stop();
                }
                if (voiceConnection) {
                    voiceConnection.destroy();
                    voiceConnection = null;
                    audioPlayer = null;
                    currentResource = null;
                }
            }
        } 
        else if (command === 'pause') {
            if (!audioPlayer || audioPlayer.state.status === AudioPlayerStatus.Paused) {
                console.log('\x1b[31m[Console Error] Music is already paused or not playing!\x1b[0m');
            } else {
                audioPlayer.pause();
                console.log('⏸️ Music paused.');
            }
        } 
        else if (command === 'resume') {
            if (!audioPlayer || audioPlayer.state.status !== AudioPlayerStatus.Paused) {
                console.log('\x1b[31m[Console Error] Music is not paused!\x1b[0m');
            } else {
                audioPlayer.unpause();
                console.log('▶️ Music resumed.');
            }
        } 
        else if (command === 'queue') {
            if (queue.length === 0) {
                console.log('🎶 The queue is empty.');
            } else {
                console.log(`\n🎶 **Current Play Queue:**`);
                console.log(`• Now Playing: ${queue[0].title}`);
                if (queue.length > 1) {
                    console.log('Up Next:');
                    for (let i = 1; i < queue.length; i++) {
                        console.log(`  ${i}. ${queue[i].title}`);
                        if (i >= 10) {
                            console.log(`  ...and ${queue.length - 11} more`);
                            break;
                        }
                    }
                }
                console.log('');
            }
        } 
        else if (command === 'loop') {
            const mode = query.toLowerCase();
            if (!mode) {
                if (loopStatus === 'none') loopStatus = 'queue';
                else if (loopStatus === 'queue') loopStatus = 'song';
                else loopStatus = 'none';
            } else if (['off', 'none', 'clear'].includes(mode)) {
                loopStatus = 'none';
            } else if (['queue', 'all'].includes(mode)) {
                loopStatus = 'queue';
            } else if (['song', 'track', 'one'].includes(mode)) {
                loopStatus = 'song';
            } else {
                console.log('\x1b[31m[Console Error] Invalid mode! Usage: loop <off|queue|song>\x1b[0m');
                rl.prompt();
                return;
            }

            const statusMap = {
                'none': 'Disabled (Normal playback)',
                'queue': 'Repeat entire queue (Queue Loop)',
                'song': 'Repeat current track (Song Loop)'
            };
            console.log(`\x1b[32m[Console Success] Loop mode updated to: "${statusMap[loopStatus]}"\x1b[0m`);
        }
        else if (command === 'shuffle') {
            if (queue.length <= 2) {
                console.log('\x1b[31m[Console Error] Not enough songs in the queue to shuffle!\x1b[0m');
            } else {
                const nowPlaying = queue[0];
                const toShuffle = queue.slice(1);
                for (let i = toShuffle.length - 1; i > 0; i--) {
                    const j = Math.floor(Math.random() * (i + 1));
                    [toShuffle[i], toShuffle[j]] = [toShuffle[j], toShuffle[i]];
                }
                queue = [nowPlaying, ...toShuffle];
                console.log(`\x1b[32m[Console Success] Shuffled ${toShuffle.length} upcoming songs!\x1b[0m`);
            }
        }
        else if (command === 'volume' || command === 'vol') {
            const val = query.trim();
            if (!val) {
                console.log(`🔊 Current Volume: ${Math.round(currentVolume * 100)}%`);
            } else {
                const parsed = parseInt(val, 10);
                if (isNaN(parsed) || parsed < 0 || parsed > 200) {
                    console.log('\x1b[31m[Console Error] Invalid volume! Specify a number between 0 and 200\x1b[0m');
                } else {
                    currentVolume = parsed / 100;
                    if (currentResource && currentResource.volume) {
                        currentResource.volume.setVolume(currentVolume);
                    }
                    console.log(`\x1b[32m[Console Success] Volume updated to: ${parsed}%\x1b[0m`);
                }
            }
        }
        else {
            console.log(`\x1b[33mUnknown command: "${command}". Type "help" for a list of commands.\x1b[0m`);
        }

        rl.prompt();
    });
}

async function joinConsoleVC(channelId) {
    try {
        const channel = await client.channels.fetch(channelId).catch(() => null);
        if (!channel) {
            console.error(`\x1b[31m[Console Error] Voice channel "${channelId}" not found or inaccessible.\x1b[0m`);
            return;
        }
        if (channel.type !== 'GUILD_VOICE' && channel.type !== 'GUILD_STAGE_VOICE') {
            console.error(`\x1b[31m[Console Error] Channel is not a voice channel (Type: ${channel.type}).\x1b[0m`);
            return;
        }

        connectToVoiceChannel(channel);
        console.log(`\x1b[32m[Console Success] Connected to VC: "${channel.name}" in Guild: "${channel.guild.name}"\x1b[0m`);
    } catch (err) {
        console.error(`\x1b[31m[Console Error] Failed to join voice channel: ${err.message}\x1b[0m`);
    }
}

// Express server for Web Dashboard control panel
const express = require('express');
const webApp = express();
const webPort = config.web_port || 3000;

webApp.use(express.json());
webApp.use(express.static(path.join(__dirname, 'public')));

// Get status API
webApp.get('/api/status', (req, res) => {
    let channelName = null;
    let guildName = null;
    if (voiceConnection) {
        const channelId = voiceConnection.joinConfig.channelId;
        const guildId = voiceConnection.joinConfig.guildId;
        const channel = client.channels.cache.get(channelId);
        if (channel) {
            channelName = channel.name;
            guildName = channel.guild.name;
        } else {
            channelName = channelId;
            guildName = guildId;
        }
    }
    res.json({
        connected: !!voiceConnection,
        channelName,
        guildName,
        currentSong: queue[0] || null,
        queue: queue.map((song, i) => ({ title: song.title, position: i })),
        paused: audioPlayer ? audioPlayer.state.status === AudioPlayerStatus.Paused : false,
        playing: audioPlayer ? audioPlayer.state.status === AudioPlayerStatus.Playing : false,
        loopStatus,
        volume: Math.round(currentVolume * 100)
    });
});

// Get owners API to resolve names for the select dropdown
webApp.get('/api/owners', async (req, res) => {
    const owners = [];
    for (const ownerId of config.owner_ids || []) {
        try {
            const user = await client.users.fetch(ownerId).catch(() => null);
            if (user) {
                owners.push({
                    id: ownerId,
                    username: user.username,
                    tag: user.tag
                });
            } else {
                owners.push({
                    id: ownerId,
                    username: `Owner (${ownerId})`,
                    tag: ownerId
                });
            }
        } catch (e) {
            owners.push({
                id: ownerId,
                username: `Owner (${ownerId})`,
                tag: ownerId
            });
        }
    }
    res.json(owners);
});

// Control API endpoints
webApp.post('/api/play', async (req, res) => {
    const { query, targetOwnerId, customVcId } = req.body;
    if (!query) {
        return res.status(400).json({ error: 'Query is required' });
    }

    try {
        let targetVc = null;
        if (targetOwnerId === 'custom' && customVcId) {
            const channel = await client.channels.fetch(customVcId).catch(() => null);
            if (channel && (channel.type === 'GUILD_VOICE' || channel.type === 'GUILD_STAGE_VOICE')) {
                targetVc = channel;
            } else {
                return res.status(400).json({ error: 'Invalid or inaccessible Voice Channel ID!' });
            }
        } else {
            // Find owner voice channel to auto-join
            targetVc = await getTargetVoiceChannel(null, targetOwnerId);
        }

        // Connect if targetVc is found and different, or connect if not connected
        if (targetVc) {
            if (!voiceConnection || voiceConnection.joinConfig.channelId !== targetVc.id) {
                connectToVoiceChannel(targetVc);
            }
        } else if (!voiceConnection) {
            return res.status(400).json({ error: 'No owner is currently in a voice channel. Please join one first!' });
        }

        const songs = await resolveSong(query);
        queue.push(...songs);

        if (queue.length === songs.length) {
            playSong(null);
        }

        res.json({ success: true, song: songs[0], count: songs.length });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

webApp.post('/api/pause', (req, res) => {
    if (!audioPlayer || audioPlayer.state.status === AudioPlayerStatus.Paused) {
        return res.status(400).json({ error: 'Music is already paused or not playing' });
    }
    audioPlayer.pause();
    res.json({ success: true });
});

webApp.post('/api/resume', (req, res) => {
    if (!audioPlayer || audioPlayer.state.status !== AudioPlayerStatus.Paused) {
        return res.status(400).json({ error: 'Music is not paused' });
    }
    audioPlayer.unpause();
    res.json({ success: true });
});

webApp.post('/api/skip', (req, res) => {
    if (!voiceConnection || !audioPlayer) {
        return res.status(400).json({ error: 'No music is currently playing' });
    }
    if (currentChildProcess) {
        currentChildProcess.kill();
        currentChildProcess = null;
    }
    audioPlayer.stop();
    res.json({ success: true });
});

webApp.post('/api/stop', (req, res) => {
    if (!voiceConnection) {
        return res.status(400).json({ error: 'Bot is not in a voice channel' });
    }
    queue = [];
    if (currentChildProcess) {
        currentChildProcess.kill();
        currentChildProcess = null;
    }
    if (audioPlayer) {
        audioPlayer.stop();
    }
    if (voiceConnection) {
        voiceConnection.destroy();
        voiceConnection = null;
        audioPlayer = null;
        currentResource = null;
    }
    res.json({ success: true });
});

webApp.post('/api/loop', (req, res) => {
    const { mode } = req.body;
    if (!['none', 'song', 'queue'].includes(mode)) {
        return res.status(400).json({ error: 'Invalid loop mode. Must be none, song, or queue' });
    }
    loopStatus = mode;
    console.log(`\x1b[32m[Web API] Loop mode updated to: "${loopStatus}"\x1b[0m`);
    res.json({ success: true, loopStatus });
});

webApp.post('/api/volume', (req, res) => {
    const { volume } = req.body;
    const parsed = parseInt(volume, 10);
    if (isNaN(parsed) || parsed < 0 || parsed > 200) {
        return res.status(400).json({ error: 'Invalid volume level. Must be between 0 and 200' });
    }
    currentVolume = parsed / 100;
    if (currentResource && currentResource.volume) {
        currentResource.volume.setVolume(currentVolume);
    }
    console.log(`\x1b[32m[Web API] Volume updated to: ${parsed}%\x1b[0m`);
    res.json({ success: true, volume: parsed });
});

webApp.post('/api/shuffle', (req, res) => {
    if (queue.length <= 2) {
        return res.status(400).json({ error: 'Not enough songs in the queue to shuffle!' });
    }
    const nowPlaying = queue[0];
    const toShuffle = queue.slice(1);
    for (let i = toShuffle.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [toShuffle[i], toShuffle[j]] = [toShuffle[j], toShuffle[i]];
    }
    queue = [nowPlaying, ...toShuffle];
    console.log(`\x1b[32m[Web API] Shuffled ${toShuffle.length} upcoming songs!\x1b[0m`);
    res.json({ success: true });
});

// Start web server helper
function startWebServer() {
    webApp.listen(webPort, () => {
        console.log(`\n\x1b[32m[Success] Web Dashboard control panel is running at: http://localhost:${webPort}\x1b[0m\n`);
    }).on('error', (err) => {
        console.warn(`\x1b[33m[Warning] Web server failed to start on port ${webPort}: ${err.message}\x1b[0m`);
    });
}

client.login(config.token).catch(err => {
    console.error('\n\x1b[31m[Error] Login failed! Check your token inside config.json\x1b[0m');
    console.error(err);
});
